### ISSUE TITLE
画像の出力

### ISSUE THREAD

**Issue by MizutoKadowaki0312** [MizutoKadowaki0312/gee_tutorial#1]
Python を用いたコードでの，衛星画像の出力を目指す．(理解までいきたい)

**Comment by MizutoKadowaki0312** [comment]
@onenechan 

[さっきpushしたファイル](https://nbviewer.jupyter.org/github/MizutoKadowaki0312/gee_tutorial/blob/main/01_visualize.ipynb)のコードでできそう！

@onenechan の個人レポジトリのコードとは少し違うみたい！

**Comment by onenechan** [comment]
めっちゃすごいーーー！！
